version: '3.1'

services:
  app:
    build:
      context: .
    ports:
      - "8002:80"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=192.168.1.159
      - DB_PORT=5432
      - DB_NAME=gm_orgnisation
      - DB_USER=gm_orgnisation
      - DB_PASS=Gini789mind
    restart: unless-stopped